# Lesson 0: INTRODUCTION


## Exercise 1
Given the vectors $a = (4,3,8,1)$ and $b = (2,2,1,6)$:


1.   Get the sum of vectors $a$ and $b$.
2.   Create a vector $c$ whose components are the values of $a$ multiplied by each corresponding element of $b$.
3.   Create a vector $d$ whose components are the values of $a$ powered to each corresponding element of $b$.



In [1]:
import numpy as np
a = np.array([4, 3, 8, 1])
b = np.array([2, 2, 1, 6])
print(a+b)
c = a * b
d = np.power(a,b)
print(c)
print(d)

[6 5 9 7]
[8 6 8 6]
[16  9  8  1]


## Exercise 2
Given $A = \begin{pmatrix} 1 & 2 & -1 \\ 1 & 0 & 1 \\ 4 & -4 & 5 \end{pmatrix}$
1.   Get its transposed matrix $A^T$.
2.   Check if $A$ has an inverse $A^{-1}$ and, if it does, get its value.
3.   Get the eigenvalues and eigenvectors of $A$.
4.   Check if, for each eigenvalue $\lambda$ and each corresponding eigenvector $v$, $Av = \lambda v$.

In [2]:
a = np.matrix([[1, 2 ,-1],[1, 0, 1], [4, -4, 5]])
print(a.I)
print(a.T)
#print(np.transpose(a))
#print(np.linalg.inv(A))
eigenvalues, eigenvectors = np.linalg.eig(a)


[[ 0.66666667 -1.          0.33333333]
 [-0.16666667  1.5        -0.33333333]
 [-0.66666667  2.         -0.33333333]]
[[ 1  1  4]
 [ 2  0 -4]
 [-1  1  5]]


### Exercise 3 
Construct a matrix $A$ of size $2 \times 3$ with random numbers.
1.   Construct a matrix $B$ as the matrix $A$ followed by an identity matrix at its right.
2.   Construct a matrix $C$ removing the odd columns of matrix $B$.
3.   Construct a matrix $D$ as the intersection of the first row of $B$ and its third and forth columns.

In [3]:
a = np.random.rand(2,3);
b = np.concatenate((a, np.eye(2)), axis=1)
c = b[:, ::2]
d = b[0,2:4]

## Exercise 4
Construct a matrix $A$ of size $4 \times 4$ with random numbers.
1.  Get the sum of the elements on each row.
2.  Get the sum of the elements on each column.
3.  Get the sum of the elements in its principal diagonal.
4.  Extract the submatrix whose diagonal are the elements $A_{1, 1}$ and $A_{2, 2}$.

In [4]:
a = np.random.rand(4,4)
print(a)
print()
print(np.sum(a,axis=1)) # por fila
print()
print(np.sum(a,axis=0)) # por columna
print() 
print(np.trace(a))
print()
print(a[:2,:2])



[[0.81179243 0.61940946 0.96965195 0.08903004]
 [0.61694332 0.64646297 0.3285516  0.23695673]
 [0.38119703 0.52745018 0.01650032 0.68544934]
 [0.96212031 0.51499616 0.72055206 0.36705169]]

[2.48988388 1.82891461 1.61059686 2.56472022]

[2.77205309 2.30831876 2.03525593 1.37848779]

1.8418074042982906

[[0.81179243 0.61940946]
 [0.61694332 0.64646297]]


## Exercise 5

Using matrices $M = \begin{pmatrix} 1& 2 & 3 & 3 \\ 2 & 2 & 0 & 0 \\ 5 & 6 & 3 & 1 \\ 0 & 2 & 0 & 5 \end{pmatrix}$ and $N = \begin{pmatrix} 1& 2 & 3 & 3 \\ -1 & 2 & 0 & 0 \\ 5 & 6 & 3 & 1 \\ 0 & 2 & 0 & 4 \end{pmatrix}$

1.  Construct a matrix $O$ whose elements $(i,j)$ are $O_{i,j} = 2M_{i,j} - 3N_{i,j}$
1.  Construct a matrix $P$ whose elements $(i,j)$ are $P_{i,j} = \frac{1}{3}M_{i,j}^3$
1.  Construct a matrix $Q$ whose elements $(i,j)$ are $Q_{i,j} = N_{i,j}-\frac{1+ \sqrt{5}}{2}$


In [5]:
m = np.matrix([[1,2,3,3],[2,2,0,0],[5,6,3,1],[0,2,0,5]])
n = np.matrix([[1,2,3,3],[-1,2,0,0],[5,6,3,1],[0,2,0,4]])
o = 2*m-3*n
p = 1/3*np.power(m,3)
q = n - ((1+np.power(5,1/2))/2)

## Exercise 6

Using the matrix $M$ from exercise 5, add to its third row the values of the first row multiplied by 3. Then, switch the first and third resulting columns.

In [6]:
print(m)
m[2,:]+=3*m[0,:]
print(m)

[[1 2 3 3]
 [2 2 0 0]
 [5 6 3 1]
 [0 2 0 5]]
[[ 1  2  3  3]
 [ 2  2  0  0]
 [ 8 12 12 10]
 [ 0  2  0  5]]


## Exercise 7
Using the matrix $N$ from exercise 5, find the minimum value of each row. Additionaly, sort the elements of each column in $N$ in descending order.

In [8]:
minValuesRow = np.min(n, axis=1)
columnasOrdenadas = np.sort(n, axis=0)[::-1]

## Exercise 8
Using the vectors $A = (1,3,5,7)$ and $B = (2,4,6,8)$, construct the matrix $C = \begin{pmatrix} 2& 4 & 6 & 8 \\ 6 & 12 & 18 & 24 \\ 10 & 20 & 30 & 40 \\ 14 & 28 & 42 & 56 \end{pmatrix}$

In [9]:
a = np.matrix([1,3,5,7])
b = np.matrix([2,4,6,8])
c = np.zeros((4,4))
multiplicar = np.array([1,3,5,7])
for i in range(4):
    c[i,:] =  c[i,:] + multiplicar[i]*b

## Exercise 9
Construct a random matrix $X$ of size $5 \times 5$. With a single instruction, replace all values of the principal diagonal with zeroes.

In [10]:
x = np.random.rand(5,5)
np.fill_diagonal(x,0)
print(x)

[[0.         0.61844321 0.21554199 0.50246547 0.61428446]
 [0.96822562 0.         0.06625661 0.08958586 0.21465932]
 [0.23925002 0.09536228 0.         0.71948919 0.03809379]
 [0.20790485 0.2656813  0.37000341 0.         0.38102169]
 [0.8594782  0.927752   0.58334397 0.34483594 0.        ]]


## Exercise 10

Given the matrix $X = \begin{pmatrix} 1&2&3&4 \\ 5&6&7&8 \\ 9&10&11&12 \\ 13&14&15&16 \end{pmatrix}$, construct matrix $Y = \begin{pmatrix} 1&1&1&1 \\ 1&6&1&1 \\ 1&1&11&1 \\ 1&1&1&16 \end{pmatrix}$

In [11]:
x=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
y=np.zeros((4,4))
for i in range(4):
    y[:,i]=np.squeeze(x[:, 1] - x[:, 0])
np.fill_diagonal(y,np.diag(x))
print(y)

[[ 1.  1.  1.  1.]
 [ 1.  6.  1.  1.]
 [ 1.  1. 11.  1.]
 [ 1.  1.  1. 16.]]


## Exercise 11
Using the vector $v = (2,4,6,8)$ and the matrix $M = \begin{pmatrix} 1&1&1&1 \\2&2&2&2 \\ 3&3&3&3 \\ 4&4&4&4 \end{pmatrix}$, construct, in a single instruction, matrix $W = \begin{pmatrix} 2&1&1&1 \\2&4&2&2 \\ 3&3&6&3 \\ 4&4&4&8 \end{pmatrix}$.


In [12]:
v=np.array([2,4,6,8])
m=np.matrix([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
w = np.concatenate((m[:, 0], m[:, 1], m[:, 2], m[:, 3]), axis=1)
np.fill_diagonal(w,v)
print(w)

[[2 1 1 1]
 [2 4 2 2]
 [3 3 6 3]
 [4 4 4 8]]


## Exercise 12
Given matrix $X = \begin{pmatrix} 1&-2&-3&4 \\ -5&6&7&-8 \\ -9&-10&11&12 \\ 13&-14&-15&-16 \end{pmatrix}$, set all negative elements to 20.

In [14]:
x=np.matrix([[1,-2,-3,4],[-5,6,7,-8],[-9,-10,11,12],[13,-14,-15,-16]])
x[x<0]=20

## Exercise 13
Given the matrix $X$ on exercise 12, set all elements greater than -5 and less than 6 to 11.

In [13]:
x[(x>-5) & (x<6)] = 11

# EXERCISES WITH POLYNOMIALS

## Exercise 14

Given the polynomials 

$p(x) = x^6 - 15x^4 + 85x^4 - 225x^3 + 274x^2 - 120x \\
q(x) = x^3-9x^2-26x-24$

1.  Represent the polynomials as `ndarrays`
2.  Get the values $p(-2), p(-3), q(-1)$
3.  Get $p(x)+q(x)$
4.  Get $p(x)-q(x)$
5.  Get $p(x)+q(x)-p(x)*q(x)$
6.  Get the result of $p$ divided by $q$.

In [15]:
p=np.array([1,-15,85,-225,274,-120,0])
q=np.array([1,-9,-26,-25])
z=np.array([1,5])
p1 = np.polyval(p,-2)
p2 = np.polyval(p,2)
q1 = np.polyval(q,-1)
print(np.polyadd(p,q))
print(np.polysub(p,q))
p=np.poly1d(p)
q=np.poly1d(q)
print(p+q-p*q) #devuelve
print(p/q) #np.polydiv ->devuelve cociente y division

[   1  -15   85 -224  265 -146  -25]
[   1  -15   85 -226  283  -94   25]
    9      8       7       6       5        4       3        2
-1 x + 24 x - 194 x + 626 x - 479 x - 1054 x + 195 x + 3995 x - 3146 x - 25
(poly1d([  1.,  -6.,  57., 157.]), poly1d([3019., 5387., 3925.]))


## Exercise 15

Given the polynomial $r(x) = (x-2)^2 (x+3)(x-7)$
1.  Represent $r$ symbolically.*
2.  Convert the symbolic representation to numerical.
3.  Get the value of $r$ divided by $s(x) = x^2 -4x-21$
4.  Get the symbolic expression of the result of the previous task.

In [23]:
r1=np.array([1,-2])
r2=np.array([1,3])
r3=np.array([1,-7])

r4=np.polymul(r2,r3)
r5=np.polynomial.polynomial.polypow(r1,2)
r=np.polymul(r4,r5)
print(np.poly1d(r))

s=np.array([1,-4,-21])
cociente,resto=np.polydiv(r,s)
print(np.polyval(cociente,5)) #x=5

   4     3     2
1 x - 8 x - 1 x + 68 x - 84
9.0


## Exercise 16
Find the absolute minimum of the polynomial $p(x) = x^2 + x + 1$.


In [24]:
p=np.array([1,1,1]) #a=1 b=1 c=1; x=-b/2a
print(np.polyval(p,-1/2))

0.75
